In [102]:
import pandas as pd

In [103]:
MAIN_FOLDER = "/home/arman/it/AI_work/analyze_data/1_turkiye_students"

In [104]:
data = pd.read_csv(f"{MAIN_FOLDER}/turkiye_students.csv")
print(data.shape)
data.head()

(5820, 33)

,instr,class,nb.repeat,attendance,difficulty,Q1,Q2,Q3,Q4,Q5,...,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,Q28
0,1,2,1,0,4,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
1,1,2,1,1,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
2,1,2,1,2,4,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
3,1,2,1,1,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
4,1,2,1,0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

в данной чистке данных я буду пытаться очистить датасет от ложных и некоректных ответов

google translator

instr: Идентификатор преподавателя; значения взяты из {1,2,3} \
class: Код курса (дескриптор); значения взяты из {1-13} \
repeat: Количество раз, когда студент проходит этот курс; значения взяты из {0,1,2,3,…} \
attendance: Код уровня посещаемости; значения из {0, 1, 2, 3, 4} \
difficulty: Уровень сложности курса, по мнению студента; значения взяты из {1,2,3,4,5} \
Q1: Содержание семестрового курса, методика преподавания и система оценки были предоставлены в начале. \
Q2: Цели и задачи курса были четко сформулированы в начале периода. \
Q3: Курс соответствовал количеству зачетных единиц, присвоенных ему. \
Q4: Курс преподавался в соответствии с программой, объявленной в первый день занятий. \
Q5: Обсуждения на занятиях, домашние задания, практические работы и исследования были удовлетворительными. \

Q6: Учебник и другие учебные материалы были достаточными и актуальными. \
Q7: Курс предусматривал полевые работы, применение полученных знаний на практике, лабораторные занятия, дискуссии и другие виды исследований. \
Q8: Тесты, задания, проекты и экзамены способствовали обучению. \
Q9: Мне очень понравились занятия, и я с удовольствием принимал активное участие в лекциях. \
Q10: Мои первоначальные ожидания от курса оправдались к концу учебного года. \
Q11: Курс был актуальным и полезным для моего профессионального развития. \
Q12: Курс помог мне взглянуть на жизнь и мир с новой точки зрения. \
Q13: Знания преподавателя были актуальными и современными. \
Q14: Преподаватель приходил на занятия подготовленным. \
Q15: Преподаватель преподавал в соответствии с объявленным планом занятий. \
Q16: Преподаватель был предан курсу и его объяснения были понятны. \
Q17: Преподаватель приходил на занятия вовремя. \

Q18: Преподаватель излагает материал плавно и доступно. \
Q19: Преподаватель эффективно использует учебное время. \
Q20: Преподаватель объясняет курс и стремится помочь студентам. \
Q21: Преподаватель демонстрирует позитивный подход к студентам. \
Q22: Преподаватель открыто и уважительно относится к мнению студентов о курсе. \
Q23: Преподаватель поощряет участие в курсе. \
Q24: Преподаватель дает соответствующие домашние задания/проекты и помогает/направляет студентов. \
Q25: Преподаватель отвечает на вопросы о курсе как во время занятий, так и вне их. \
Q26: Система оценки преподавателя (вопросы на промежуточном и итоговом экзаменах, проекты, задания и т. д.) эффективно измеряет достижение целей курса. \
Q27: Преподаватель предоставляет решения к экзаменам и обсуждает их со студентами. \
Q28: Преподаватель относится ко всем студентам справедливо и объективно. \
Вопросы Q1-Q28 относятся к типу Ликерта, то есть значения взяты из множества {1,2,3,4,5}.

In [105]:
# если в классе >50% студентов отвечали на субъективные вопросы одинакого, то мы не принимаем другие ответы
# например
# Q1: Содержание семестрового курса, методика преподавания и система оценки были предоставлены в начале.
# Q2: Цели и задачи курса были четко сформулированы в начале периода.
# Q3: Курс соответствовал количеству зачетных единиц, присвоенных ему.
# Q4: Курс преподавался в соответствии с программой, объявленной в первый день занятий.
# Q17: Преподаватель приходил на занятия вовремя.
print(data.shape)
for student_group in range(1,13+1):
    data_for_student_group = data[(data["class"]==student_group)]
    print(f"в классе {student_group} {data_for_student_group.shape[0]} студентов")
    class_quantity = data_for_student_group.shape[0]
    need_quantity = class_quantity * 0.5
    for question in ["Q1", "Q2", "Q3", "Q4", "Q17"]:
        print(f"в вопросе {question}")
        rate_static = [None, 0, 0, 0, 0, 0]
        for popular_rate in range(1,5+1):
            statistik = data_for_student_group[data_for_student_group[question]==popular_rate].shape[0] / class_quantity * 100
            print(f"оценкой {popular_rate} ответили {statistik:.2f}% студентов")
            popular_rate_quantity = data_for_student_group[data_for_student_group[question]==popular_rate].shape[0]
            if popular_rate_quantity >= need_quantity:
                data_for_student_group[question] =\
                    data_for_student_group[question].map(lambda _: popular_rate)
                changed = class_quantity - popular_rate_quantity
                print(f"поменяли {changed} в вопросе {question} на ответ {popular_rate}, класс {student_group}")
                break
        print("-"*50)
print(data.shape)
data.head()

(5820, 33)
в классе 1 303 студентов
в вопросе Q1
оценкой 1 ответили 15.84% студентов
оценкой 2 ответили 12.21% студентов
оценкой 3 ответили 27.06% студентов
оценкой 4 ответили 28.71% студентов
оценкой 5 ответили 16.17% студентов
--------------------------------------------------
в вопросе Q2
оценкой 1 ответили 10.89% студентов
оценкой 2 ответили 9.57% студентов
оценкой 3 ответили 29.37% студентов
оценкой 4 ответили 32.67% студентов
оценкой 5 ответили 17.49% студентов
--------------------------------------------------
в вопросе Q3
оценкой 1 ответили 9.57% студентов
оценкой 2 ответили 9.90% студентов
оценкой 3 ответили 29.37% студентов
оценкой 4 ответили 33.33% студентов
оценкой 5 ответили 17.82% студентов
--------------------------------------------------
в вопросе Q4
оценкой 1 ответили 11.88% студентов
оценкой 2 ответили 10.23% студентов
оценкой 3 ответили 29.04% студентов
оценкой 4 ответили 30.69% студентов
оценкой 5 ответили 18.15% студентов
--------------------------------------------------
в вопросе Q17
оценкой 1 ответили 9.57% студентов
оценкой 2 ответили 5.61% студентов
оценкой 3 ответили 25.41% студентов
оценкой 4 ответили 36.63% студентов
оценкой 5 ответили 22.77% студентов
--------------------------------------------------
в классе 2 140 студентов
в вопросе Q1
оценкой 1 ответили 16.43% студентов
оценкой 2 ответили 10.71% студентов
оценкой 3 ответили 19.29% студентов
оценкой 4 ответили 21.43% студентов
оценкой 5 ответили 32.14% студентов
--------------------------------------------------
в вопросе Q2
оценкой 1 ответили 15.71% студентов
оценкой 2 ответили 6.43% студентов
оценкой 3 ответили 22.86% студентов
оценкой 4 ответили 22.86% студентов
оценкой 5 ответили 32.14% студентов
--------------------------------------------------
в вопросе Q3
оценкой 1 ответили 15.00% студентов
оценкой 2 ответили 8.57% студентов
оценкой 3 ответили 20.00% студентов
оценкой 4 ответили 25.71% студентов
оценкой 5 ответили 30.71% студентов
--------------------------------------------------
в вопросе Q4
оценкой 1 ответили 15.00% студентов
оценкой 2 ответили 10.00% студентов
оценкой 3 ответили 20.00% студентов
оценкой 4 ответили 24.29% студентов
оценкой 5 ответили 30.71% студентов
--------------------------------------------------
в вопросе Q17
оценкой 1 ответили 12.14% студентов
оценкой 2 ответили 7.14% студентов
оценкой 3 ответили 17.14% студентов
оценкой 4 ответили 24.29% студентов
оценкой 5 ответили 39.29% студентов
--------------------------------------------------
в классе 3 904 студентов
в вопросе Q1
оценкой 1 ответили 22.68% студентов
оценкой 2 ответили 15.27% студентов
оценкой 3 ответили 30.97% студентов
оценкой 4 ответили 18.69% студентов
оценкой 5 ответили 12.39% студентов
--------------------------------------------------
в вопросе Q2
оценкой 1 ответили 19.69% студентов
оценкой 2 ответили 14.82% студентов
оценкой 3 ответили 31.86% студентов
оценкой 4 ответили 21.90% студентов
оценкой 5 ответили 11.73% студентов
--------------------------------------------------
в вопросе Q3
оценкой 1 ответили 18.03% студентов
оценкой 2 ответили 12.50% студентов
оценкой 3 ответили 33.96% студентов
оценкой 4 ответили 23.01% студентов
оценкой 5 ответили 12.50% студентов
--------------------------------------------------
в вопросе Q4
оценкой 1 ответили 18.03% студентов
оценкой 2 ответили 15.93% студентов
оценкой 3 ответили 32.74% студентов
оценкой 4 ответили 21.24% студентов
оценкой 5 ответили 12.06% студентов
--------------------------------------------------
в вопросе Q17
оценкой 1 ответили 16.26% студентов
оценкой 2 ответили 10.29% студентов
оценкой 3 ответили 30.42% студентов
оценкой 4 ответили 28.54% студентов
оценкой 5 ответили 14.49% студентов
--------------------------------------------------
в классе 4 187 студентов
в вопросе Q1
оценкой 1 ответили 29.41% студентов
оценкой 2 ответили 23.53% студентов
оценкой 3 ответили 25.13% студентов
оценкой 4 ответили 18.18% студентов
оценкой 5 ответили 3.74% студентов
--------------------------------------------------
в вопросе Q2
оценкой 1 ответили 18.72% студентов
оценкой 2 ответили 25.67% студентов
оценкой 3 ответили 32.09% студентов
оценкой 4 ответили 20.86% студентов
оценкой 5 ответили 2.67% студентов
--------------------------------------------------
в вопросе Q3
оценкой 1 ответили 12.30% студентов
оценкой 2 ответили 20.32% студентов
оценкой 3 ответили 37.43% студентов
оценкой 4 ответили 26.20% студентов
оценкой 5 ответили 3.74% студентов
--------------------------------------------------
в вопросе Q4
оценкой 1 ответили 21.39% студентов
оценкой 2 ответили 20.86% студентов
оценкой 3 ответили 33.69% студентов
оценкой 4 ответили 21.39% студентов
оценкой 5 ответили 2.67% студентов
--------------------------------------------------
в вопросе Q17
оценкой 1 ответили 9.09% студентов
оценкой 2 ответили 7.49% студентов
оценкой 3 ответили 31.02% студентов
оценкой 4 ответили 37.97% студентов
оценкой 5 ответили 14.44% студентов
--------------------------------------------------
в классе 5 656 студентов
в вопросе Q1
оценкой 1 ответили 16.77% студентов
оценкой 2 ответили 17.07% студентов
оценкой 3 ответили 26.98% студентов
оценкой 4 ответили 24.70% студентов
оценкой 5 ответили 14.48% студентов
--------------------------------------------------
в вопросе Q2
оценкой 1 ответили 13.26% студентов
оценкой 2 ответили 15.24% студентов
оценкой 3 ответили 29.57% студентов
оценкой 4 ответили 27.44% студентов
оценкой 5 ответили 14.48% студентов
--------------------------------------------------
в вопросе Q3
оценкой 1 ответили 12.65% студентов
оценкой 2 ответили 17.23% студентов
оценкой 3 ответили 29.88% студентов
оценкой 4 ответили 25.91% студентов
оценкой 5 ответили 14.33% студентов
--------------------------------------------------
в вопросе Q4
оценкой 1 ответили 11.74% студентов
оценкой 2 ответили 16.31% студентов
оценкой 3 ответили 28.81% студентов
оценкой 4 ответили 28.51% студентов
оценкой 5 ответили 14.63% студентов
--------------------------------------------------
в вопросе Q17
оценкой 1 ответили 9.91% студентов
оценкой 2 ответили 10.98% студентов
оценкой 3 ответили 26.37% студентов
оценкой 4 ответили 33.23% студентов
оценкой 5 ответили 19.51% студентов
--------------------------------------------------
в классе 6 558 студентов
в вопросе Q1
оценкой 1 ответили 18.46% студентов
оценкой 2 ответили 11.65% студентов
оценкой 3 ответили 27.06% студентов
оценкой 4 ответили 27.24% студентов
оценкой 5 ответили 15.59% студентов
--------------------------------------------------
в вопросе Q2
оценкой 1 ответили 12.37% студентов
оценкой 2 ответили 10.75% студентов
оценкой 3 ответили 28.67% студентов
оценкой 4 ответили 31.90% студентов
оценкой 5 ответили 16.31% студентов
--------------------------------------------------
в вопросе Q3
оценкой 1 ответили 10.57% студентов
оценкой 2 ответили 9.68% студентов
оценкой 3 ответили 27.60% студентов
оценкой 4 ответили 33.51% студентов
оценкой 5 ответили 18.64% студентов
--------------------------------------------------
в вопросе Q4
оценкой 1 ответили 12.54% студентов
оценкой 2 ответили 10.39% студентов
оценкой 3 ответили 29.93% студентов
оценкой 4 ответили 31.18% студентов
оценкой 5 ответили 15.95% студентов
--------------------------------------------------
в вопросе Q17
оценкой 1 ответили 9.68% студентов
оценкой 2 ответили 8.42% студентов
оценкой 3 ответили 23.30% студентов
оценкой 4 ответили 35.66% студентов
оценкой 5 ответили 22.94% студентов
--------------------------------------------------
в классе 7 187 студентов
в вопросе Q1
оценкой 1 ответили 25.13% студентов
оценкой 2 ответили 16.04% студентов
оценкой 3 ответили 28.88% студентов
оценкой 4 ответили 20.86% студентов
оценкой 5 ответили 9.09% студентов
--------------------------------------------------
в вопросе Q2
оценкой 1 ответили 23.53% студентов
оценкой 2 ответили 11.23% студентов
оценкой 3 ответили 28.34% студентов
оценкой 4 ответили 25.13% студентов
оценкой 5 ответили 11.76% студентов
--------------------------------------------------
в вопросе Q3
оценкой 1 ответили 19.25% студентов
оценкой 2 ответили 6.42% студентов
оценкой 3 ответили 32.62% студентов
оценкой 4 ответили 26.74% студентов
оценкой 5 ответили 14.97% студентов
--------------------------------------------------
в вопросе Q4
оценкой 1 ответили 22.46% студентов
оценкой 2 ответили 13.37% студентов
оценкой 3 ответили 27.81% студентов
оценкой 4 ответили 24.60% студентов
оценкой 5 ответили 11.76% студентов
--------------------------------------------------
в вопросе Q17
оценкой 1 ответили 18.18% студентов
оценкой 2 ответили 5.88% студентов
оценкой 3 ответили 21.39% студентов
оценкой 4 ответили 32.62% студентов
оценкой 5 ответили 21.93% студентов
--------------------------------------------------
в классе 8 500 студентов
в вопросе Q1
оценкой 1 ответили 25.80% студентов
оценкой 2 ответили 21.40% студентов
оценкой 3 ответили 22.20% студентов
оценкой 4 ответили 19.00% студентов
оценкой 5 ответили 11.60% студентов
--------------------------------------------------
в вопросе Q2
оценкой 1 ответили 17.20% студентов
оценкой 2 ответили 16.00% студентов
оценкой 3 ответили 27.60% студентов
оценкой 4 ответили 26.00% студентов
оценкой 5 ответили 13.20% студентов
--------------------------------------------------
в вопросе Q3
оценкой 1 ответили 10.20% студентов
оценкой 2 ответили 11.80% студентов
оценкой 3 ответили 28.40% студентов
оценкой 4 ответили 34.00% студентов
оценкой 5 ответили 15.60% студентов
--------------------------------------------------
в вопросе Q4
оценкой 1 ответили 18.00% студентов
оценкой 2 ответили 17.80% студентов
оценкой 3 ответили 23.40% студентов
оценкой 4 ответили 26.00% студентов
оценкой 5 ответили 14.80% студентов
--------------------------------------------------
в вопросе Q17
оценкой 1 ответили 7.20% студентов
оценкой 2 ответили 6.00% студентов
оценкой 3 ответили 19.20% студентов
оценкой 4 ответили 38.60% студентов
оценкой 5 ответили 29.00% студентов
--------------------------------------------------
в классе 9 571 студентов
в вопросе Q1
оценкой 1 ответили 20.67% студентов
оценкой 2 ответили 18.74% студентов
оценкой 3 ответили 28.90% студентов
оценкой 4 ответили 18.39% студентов
оценкой 5 ответили 13.31% студентов
--------------------------------------------------
в вопросе Q2
оценкой 1 ответили 15.76% студентов
оценкой 2 ответили 16.64% студентов
оценкой 3 ответили 31.00% студентов
оценкой 4 ответили 23.29% студентов
оценкой 5 ответили 13.31% студентов
--------------------------------------------------
в вопросе Q3
оценкой 1 ответили 12.43% студентов
оценкой 2 ответили 9.98% студентов
оценкой 3 ответили 34.50% студентов
оценкой 4 ответили 29.60% студентов
оценкой 5 ответили 13.49% студентов
--------------------------------------------------
в вопросе Q4
оценкой 1 ответили 15.41% студентов
оценкой 2 ответили 14.54% студентов
оценкой 3 ответили 31.52% студентов
оценкой 4 ответили 25.04% студентов
оценкой 5 ответили 13.49% студентов
--------------------------------------------------
в вопросе Q17
оценкой 1 ответили 10.51% студентов
оценкой 2 ответили 7.71% студентов
оценкой 3 ответили 29.42% студентов
оценкой 4 ответили 32.40% студентов
оценкой 5 ответили 19.96% студентов
--------------------------------------------------
в классе 10 448 студентов
в вопросе Q1
оценкой 1 ответили 12.95% студентов
оценкой 2 ответили 11.38% студентов
оценкой 3 ответили 22.10% студентов
оценкой 4 ответили 33.71% студентов
оценкой 5 ответили 19.87% студентов
--------------------------------------------------
в вопросе Q2
оценкой 1 ответили 11.61% студентов
оценкой 2 ответили 10.04% студентов
оценкой 3 ответили 23.44% студентов
оценкой 4 ответили 34.38% студентов
оценкой 5 ответили 20.54% студентов
--------------------------------------------------
в вопросе Q3
оценкой 1 ответили 11.61% студентов
оценкой 2 ответили 10.49% студентов
оценкой 3 ответили 22.32% студентов
оценкой 4 ответили 33.93% студентов
оценкой 5 ответили 21.65% студентов
--------------------------------------------------
в вопросе Q4
оценкой 1 ответили 10.71% студентов
оценкой 2 ответили 11.16% студентов
оценкой 3 ответили 24.78% студентов
оценкой 4 ответили 32.81% студентов
оценкой 5 ответили 20.54% студентов
--------------------------------------------------
в вопросе Q17
оценкой 1 ответили 10.49% студентов
оценкой 2 ответили 10.27% студентов
оценкой 3 ответили 19.87% студентов
оценкой 4 ответили 35.27% студентов
оценкой 5 ответили 24.11% студентов
--------------------------------------------------
в классе 11 484 студентов
в вопросе Q1
оценкой 1 ответили 16.32% студентов
оценкой 2 ответили 11.57% студентов
оценкой 3 ответили 28.51% студентов
оценкой 4 ответили 28.10% студентов
оценкой 5 ответили 15.50% студентов
--------------------------------------------------
в вопросе Q2
оценкой 1 ответили 12.40% студентов
оценкой 2 ответили 10.33% студентов
оценкой 3 ответили 30.37% студентов
оценкой 4 ответили 30.79% студентов
оценкой 5 ответили 16.12% студентов
--------------------------------------------------
в вопросе Q3
оценкой 1 ответили 11.57% студентов
оценкой 2 ответили 8.06% студентов
оценкой 3 ответили 29.75% студентов
оценкой 4 ответили 34.92% студентов
оценкой 5 ответили 15.70% студентов
--------------------------------------------------
в вопросе Q4
оценкой 1 ответили 13.22% студентов
оценкой 2 ответили 10.54% студентов
оценкой 3 ответили 29.34% студентов
оценкой 4 ответили 32.02% студентов
оценкой 5 ответили 14.88% студентов
--------------------------------------------------
в вопросе Q17
оценкой 1 ответили 8.47% студентов
оценкой 2 ответили 5.37% студентов
оценкой 3 ответили 26.24% студентов
оценкой 4 ответили 37.60% студентов
оценкой 5 ответили 22.31% студентов
--------------------------------------------------
в классе 12 41 студентов
в вопросе Q1
оценкой 1 ответили 21.95% студентов
оценкой 2 ответили 21.95% студентов
оценкой 3 ответили 21.95% студентов
оценкой 4 ответили 24.39% студентов
оценкой 5 ответили 9.76% студентов
--------------------------------------------------
в вопросе Q2
оценкой 1 ответили 19.51% студентов
оценкой 2 ответили 14.63% студентов
оценкой 3 ответили 26.83% студентов
оценкой 4 ответили 24.39% студентов
оценкой 5 ответили 14.63% студентов
--------------------------------------------------
в вопросе Q3
оценкой 1 ответили 19.51% студентов
оценкой 2 ответили 9.76% студентов
оценкой 3 ответили 31.71% студентов
оценкой 4 ответили 29.27% студентов
оценкой 5 ответили 9.76% студентов
--------------------------------------------------
в вопросе Q4
оценкой 1 ответили 19.51% студентов
оценкой 2 ответили 17.07% студентов
оценкой 3 ответили 26.83% студентов
оценкой 4 ответили 26.83% студентов
оценкой 5 ответили 9.76% студентов
--------------------------------------------------
в вопросе Q17
оценкой 1 ответили 19.51% студентов
оценкой 2 ответили 9.76% студентов
оценкой 3 ответили 24.39% студентов
оценкой 4 ответили 26.83% студентов
оценкой 5 ответили 19.51% студентов
--------------------------------------------------
в классе 13 841 студентов
в вопросе Q1
оценкой 1 ответили 30.80% студентов
оценкой 2 ответили 13.67% студентов
оценкой 3 ответили 26.52% студентов
оценкой 4 ответили 14.51% студентов
оценкой 5 ответили 14.51% студентов
--------------------------------------------------
в вопросе Q2
оценкой 1 ответили 26.40% студентов
оценкой 2 ответили 14.63% студентов
оценкой 3 ответили 26.99% студентов
оценкой 4 ответили 18.43% студентов
оценкой 5 ответили 13.56% студентов
--------------------------------------------------
в вопросе Q3
оценкой 1 ответили 24.14% студентов
оценкой 2 ответили 12.49% студентов
оценкой 3 ответили 29.13% студентов
оценкой 4 ответили 19.74% студентов
оценкой 5 ответили 14.51% студентов
--------------------------------------------------
в вопросе Q4
оценкой 1 ответили 26.52% студентов
оценкой 2 ответили 13.20% студентов
оценкой 3 ответили 27.35% студентов
оценкой 4 ответили 18.19% студентов
оценкой 5 ответили 14.74% студентов
--------------------------------------------------
в вопросе Q17
оценкой 1 ответили 23.07% студентов
оценкой 2 ответили 10.11% студентов
оценкой 3 ответили 26.16% студентов
оценкой 4 ответили 20.57% студентов
оценкой 5 ответили 20.10% студентов
--------------------------------------------------
(5820, 33)

,instr,class,nb.repeat,attendance,difficulty,Q1,Q2,Q3,Q4,Q5,...,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,Q28
0,1,2,1,0,4,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
1,1,2,1,1,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
2,1,2,1,2,4,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
3,1,2,1,1,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
4,1,2,1,0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [106]:
# очищаем ответы студентов с нулевым уровнем посещаемости
print(data.shape)
data = data[(data["attendance"]!=0)]
print(data.shape)
data.head()

(5820, 33)
(3918, 33)

,instr,class,nb.repeat,attendance,difficulty,Q1,Q2,Q3,Q4,Q5,...,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,Q28
1,1,2,1,1,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
2,1,2,1,2,4,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
3,1,2,1,1,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
5,1,2,1,3,3,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
6,1,2,1,1,3,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4

In [107]:
# очищаем ответы студентов, которые не посещали курс
print(data.shape)
data = data[(data["nb.repeat"]!=0)]
print(data.shape)
data.head()

(3918, 33)
(3918, 33)

,instr,class,nb.repeat,attendance,difficulty,Q1,Q2,Q3,Q4,Q5,...,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,Q28
1,1,2,1,1,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
2,1,2,1,2,4,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
3,1,2,1,1,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
5,1,2,1,3,3,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
6,1,2,1,1,3,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4

In [108]:
# очищаем ответы студентов, которые проставили на все вопросы одинаковые ответы, по типу 1,1,1,1,1,1, или 5,5,5,5,5,
# потому что это намекает на то, что студент не сильно задумывался над вопросами
print(data.shape)
to_delete = []
for index, row in data.iterrows():
    statistic = {}
    for q in [f"Q{i}" for i in range(1,28+1)]:
        statistic[row[q]] = statistic.get(row[q], 0) + 1
    if any(v == 28 for v in statistic.values()):
        to_delete.append(index)
data = data.drop(to_delete)
print(data.shape)
data.head()

(3918, 33)

(2094, 33)

,instr,class,nb.repeat,attendance,difficulty,Q1,Q2,Q3,Q4,Q5,...,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,Q28
8,1,2,1,1,3,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
14,1,2,1,2,3,1,1,1,1,1,...,2,3,3,3,2,2,1,1,1,1
15,1,2,1,3,4,5,5,4,4,5,...,5,4,4,5,5,4,4,4,5,4
22,1,2,1,3,3,3,3,3,3,3,...,3,2,1,1,1,3,2,2,2,2
23,1,2,1,2,4,5,3,3,3,2,...,2,2,4,4,5,5,4,4,5,5